-- MySQL Script generated by MySQL Workbench
-- Wed Dec 18 11:57:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`genre` (
  `idgenre` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`realisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`realisateur` (
  `idrealisateur` INT NOT NULL AUTO_INCREMENT,
  `realisateur` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idrealisateur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`films` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(250) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `date_sortie` VARCHAR(45) NOT NULL,
  `genre_idgenre` INT NOT NULL,
  `realisateur_idrealisateur` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_films_genre_idx` (`genre_idgenre` ASC) ,
  INDEX `fk_films_realisateur1_idx` (`realisateur_idrealisateur` ASC) ,
  CONSTRAINT `fk_films_genre`
    FOREIGN KEY (`genre_idgenre`)
    REFERENCES `mydb`.`genre` (`idgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_films_realisateur1`
    FOREIGN KEY (`realisateur_idrealisateur`)
    REFERENCES `mydb`.`realisateur` (`idrealisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
